# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\ui files\UiMainTabWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAbstractItemView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Cinemas = QtWidgets.QWidget()
        self.Cinemas.setObjectName("Cinemas")
        self.all_sessions_tb = QtWidgets.QTableWidget(self.Cinemas)
        self.all_sessions_tb.setGeometry(QtCore.QRect(20, 80, 701, 280))
        self.all_sessions_tb.setObjectName("all_sessions_tb")
        self.all_sessions_tb.setColumnCount(7)
        self.all_sessions_tb.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.all_sessions_tb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.all_sessions_tb.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_sessions_tb.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_sessions_tb.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_sessions_tb.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_sessions_tb.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_sessions_tb.setHorizontalHeaderItem(6, item)
        self.all_sessions_tb.horizontalHeader().setDefaultSectionSize(100)
        self.message_lb = QtWidgets.QLabel(self.Cinemas)
        self.message_lb.setGeometry(QtCore.QRect(330, 380, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.message_lb.setFont(font)
        self.message_lb.setText("")
        self.message_lb.setObjectName("message_lb")
        self.theatreName_lb = QtWidgets.QLabel(self.Cinemas)
        self.theatreName_lb.setGeometry(QtCore.QRect(30, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.theatreName_lb.setFont(font)
        self.theatreName_lb.setObjectName("theatreName_lb")
        self.sell_tickets_btn = QtWidgets.QPushButton(self.Cinemas)
        self.sell_tickets_btn.setGeometry(QtCore.QRect(30, 370, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sell_tickets_btn.setFont(font)
        self.sell_tickets_btn.setObjectName("sell_tickets_btn")
        self.tabWidget.addTab(self.Cinemas, "")
        self.Halls = QtWidgets.QWidget()
        self.Halls.setObjectName("Halls")
        self.new_session_btn = QtWidgets.QPushButton(self.Halls)
        self.new_session_btn.setGeometry(QtCore.QRect(30, 370, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.new_session_btn.setFont(font)
        self.new_session_btn.setObjectName("new_session_btn")
        self.delete_session_btn = QtWidgets.QPushButton(self.Halls)
        self.delete_session_btn.setGeometry(QtCore.QRect(190, 370, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_session_btn.setFont(font)
        self.delete_session_btn.setObjectName("delete_session_btn")
        self.edit_session_btn = QtWidgets.QPushButton(self.Halls)
        self.edit_session_btn.setGeometry(QtCore.QRect(350, 370, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_session_btn.setFont(font)
        self.edit_session_btn.setObjectName("edit_session_btn")
        self.hall_sessions_tb = QtWidgets.QTableWidget(self.Halls)
        self.hall_sessions_tb.setGeometry(QtCore.QRect(20, 80, 702, 281))
        self.hall_sessions_tb.setAutoScroll(True)
        self.hall_sessions_tb.setObjectName("hall_sessions_tb")
        self.hall_sessions_tb.setColumnCount(6)
        self.hall_sessions_tb.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hall_sessions_tb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hall_sessions_tb.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hall_sessions_tb.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hall_sessions_tb.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hall_sessions_tb.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hall_sessions_tb.setHorizontalHeaderItem(5, item)
        self.hall_sessions_tb.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.hall_sessions_tb.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.hall_name_lb = QtWidgets.QLabel(self.Halls)
        self.hall_name_lb.setGeometry(QtCore.QRect(30, 13, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hall_name_lb.setFont(font)
        self.hall_name_lb.setObjectName("hall_name_lb")
        self.halls_comboBox = QtWidgets.QComboBox(self.Halls)
        self.halls_comboBox.setGeometry(QtCore.QRect(195, 18, 141, 22))
        self.halls_comboBox.setObjectName("comboBox")
        self.new_hall_btn = QtWidgets.QPushButton(self.Halls)
        self.new_hall_btn.setGeometry(QtCore.QRect(350, 17, 24, 24))
        self.new_hall_btn.setObjectName("new_hall_btn")
        self.del_hall_btn = QtWidgets.QPushButton(self.Halls)
        self.del_hall_btn.setGeometry(QtCore.QRect(388, 17, 24, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.del_hall_btn.setFont(font)
        self.del_hall_btn.setObjectName("del_hall_btn")
        self.tabWidget.addTab(self.Halls, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.all_sessions_tb.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.all_sessions_tb.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название фильма"))
        item = self.all_sessions_tb.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Время начала"))
        item = self.all_sessions_tb.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Длительность"))
        item = self.all_sessions_tb.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Зал"))
        item = self.all_sessions_tb.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Кол-во свободных мест"))
        item = self.all_sessions_tb.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Цена за билет"))
        self.theatreName_lb.setText(_translate("MainWindow", "Кинотеатр такой-то"))
        self.sell_tickets_btn.setText(_translate("MainWindow", "Продать билеты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Cinemas), _translate("MainWindow", "Tab 1"))
        self.new_session_btn.setText(_translate("MainWindow", "Новый сеанс"))
        self.delete_session_btn.setText(_translate("MainWindow", "Удалить сеанс"))
        self.edit_session_btn.setText(_translate("MainWindow", "Изменить сеанс"))
        item = self.hall_sessions_tb.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.hall_sessions_tb.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название фильма"))
        item = self.hall_sessions_tb.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Время начала"))
        item = self.hall_sessions_tb.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Длительность"))
        item = self.hall_sessions_tb.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Кол-во свободных мест"))
        item = self.hall_sessions_tb.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Цена за билет"))
        self.hall_name_lb.setText(_translate("MainWindow", "Зал"))
        self.new_hall_btn.setText(_translate("MainWindow", "+"))
        self.del_hall_btn.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Halls), _translate("MainWindow", "Tab 2"))
